# Aplying the recomendator system


This notebook is a part of the project Library recomender system. To generet the datases used in this notebook, we have used spiders to colect biblographis registers and users trasactions over many library sites. The bibliograthic registers have been already unificated and associated with a unique identifier class "codObra";

In the previously we used the scikit learning liubrary to reduce the dimentionality of the one hot *WORK vz USER rating matriz . The original one has 1,4 milion of dimention, we reducetd it to 10 dimention. In this notebook, using the *work dataset ratings with 10 dimentions, we aplly nearest neighborhood calgrtinms to find for each work the neares one. These user filter funcitionalit is particular usefull to catalog sistes where show other itens base in pther experience " who saw that also saw : "




<font color=blue>*the same book with diferent editions were agruped in "Work" and has the "codObra" as unique identifier</font>
  



## Firsts let load the bookWeight data set  Aplying the recomendator system

1. id is the dataset order
2. codobra is the "Work" identifier
3. c1, c2 ... c10 are the Weight in reducted vector space with 10 dimentions


In [1]:
import pandas as pd 

booksweight = pd.read_csv('bookWeight.csv')  # doctest: +SKIP
booksweight.shape

(133989, 12)

In [2]:
booksweight.head(4)


id  codobra        c1        c2        c3        c4        c5        c6  \
0   0      110 -0.069944  0.261876  0.279082 -0.003079  0.204972 -0.209111   
1   1      140  0.927947  0.973363 -1.187703 -0.668665 -0.070719 -0.089884   
2   2      160  1.155321 -0.011052  0.533303  0.634104 -1.456100  0.430736   
3   3      190 -0.260877  0.295407  0.194097  0.061888  0.233164 -0.171829   

         c7        c8        c9       c10  
0  0.039038 -0.186838 -0.042609 -0.014002  
1 -0.468329  0.746488  0.077941  0.817792  
2  1.472087 -1.881912  0.803114  1.844294  
3 -0.026542 -0.209496  0.041619  0.115344


<font color=blue font-size = 19px>* Lets transform to numoy array to use sklearn library </font>

In [3]:
weights =  booksweight.to_numpy()[0:, 2:]

print(weights.shape)
print(booksweight.shape)
#-0.069944	0.261876	0.279082
weights[0:2]


(133989, 10)
(133989, 12)


array([[-0.06994427,  0.26187602,  0.27908191, -0.00307914,  0.20497191,
        -0.2091108 ,  0.03903817, -0.18683849, -0.04260883, -0.01400245],
       [ 0.92794734,  0.97336334, -1.18770325, -0.66866517, -0.07071923,
        -0.08988411, -0.46832892,  0.74648798,  0.07794056,  0.81779218]])

<font color=blue font-size = 19px>NearestNeighbors find the points (works)  Nearest of each point </font>

In [4]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

nbrs = NearestNeighbors(n_neighbors=10, algorithm='auto',n_jobs=6  ).fit(weights)
distances, indices = nbrs.kneighbors(weights)

print(distances[0])
print(indices[0])




[0.         0.06136852 0.09225836 0.09280618 0.09414747 0.09417006
 0.09453893 0.09453893 0.09479223 0.0998378 ]
[     0  51035  32410  60844  27091  32119  70423 112977  45826 104192]


In [5]:
print(distances[2233])
print(indices[2233])


[0.         2.33108207 2.5510443  2.55409957 2.72099495 2.77264112
 2.84755236 2.90062697 2.9559641  3.05751834]
[  2233  84279 100583  40390 132411  55125 106848  86715  45278 102478]



## Let's seen some examples  

In [6]:
booksweight.set_index('codobra', inplace=True)

In [7]:
books = {
    1735: 'moreninha',
    1522 : "dom casmurro",
    2172 : "Quincas Borba: ",
    278  : 'Quem Mexeu no Meu Queijo?', 
    5310: 'Como Fazer Amigos e Influenciar Pessoas',
    1117  : 'Fundamentos da metafisica dos costumes ',
        
    17180 : 'pai rico',
    9948 : 'Convite a Filosofia:',
    
    277  : 'Grande sertao Veredas',
    2873:'Harry Potter e a Ordem da Fenix',
    6970: 'Matematica divertida e curiosa',
    223802: 'matematica fundamentos ' ,
    24459: 'O que e literatura:'  ,
    26526: 'A guerra dos tronos',
    30353: 'O Que e Ideologia',
      
    
      
}



## Reduzindo a dimensionalida para 2 e colocando nosso exemplos em um gráfico




In [8]:
import pandas as pd 

obreas = pd.read_csv('/home/JobResults/arrumatransacional/obra.cvs')  # doctest: +SKIP
obreas.set_index('codobra', inplace=True)

obreas.head(3)

def getTitobra(codobra):
    try:
        return obreas.loc[codobra]['tit']
    except:
        return ""

def getindexCodObra(codobra):
    return int(booksweight.loc[codobra]['id'])



def getCodObra(indice):
    return booksweight.iloc[indice].name


    

In [9]:
def getitulorec(codobra):

    indice =  getindexCodObra(codobra)
    indiceobra  = indices[indice]
    result = ''

    for indtit in indiceobra:
        codobrat =  getCodObra(indtit)
        titulo =  getTitobra(codobrat)
        result =  result + '   ' +str(codobrat) +  ' ' +titulo + '\n'

    
    return result[3:]



resultado = getitulorec(140)
print(resultado)






140 Ritinha_bonitinha
   100059 Personagens_encantados_II
   2704 Tempus_Fugit
   218875 Lições_de_texto
   223381 Venturas_e_desventuras_de_Zé_Teixeira
   177118 O_amor_venceu
   62730 Robin_Hood
   367635 
   287745 Exercícios_abdominais
   164244 A_tartaruga



In [10]:


for x in books:
    resultado = getitulorec(x)
    print(resultado )
    
    
    



1735 Memorias_postumas_de_Bras_Cubas
   133654 Til
   331873 A_cidade_e_as_serras
   1522 Dom_Casmurro
   1828 Vidas_secas
   297063 Antes_que_o_amor_acabe
   254191 Concerto_para_arranha-céus
   59273 Memórias_de_um_sargento_de_milícias
   374594 
   10693 Poirot_Investiga

1522 Dom_Casmurro
   59273 Memórias_de_um_sargento_de_milícias
   1828 Vidas_secas
   1735 Memorias_postumas_de_Bras_Cubas
   9152 O_Morte_na_praia
   133654 Til
   28863 A_Mao_Misteriosa
   7190 Encontro_com_a_Morte
   9298 Noite_sem_fim
   8974 O_Um_passe_de_magica

2172 Quincas_Borba
   335675 Gramática_prática_da_língua_inglesa
   114234 Drummond_Frente_e_Verso
   96938 Estrutura_social_mobilidade_e_raça
   44316 Realismo_e_anti-realismo_na_literatura_brasileira
   56319 Conviver_e_Melhorar
   89191 O_conhecimento_no_cotidiano
   108518 Censura_autoritarismo_y_cultura
   199663 Navalhanaliga
   238569 Processo

278 Quem_Mexeu_no_Meu_Queijo?
   26836 O_Ultimo_Adeus_de_Sherlock_Holmes
   2210 O_Codigo_Da_Vinci
  


## Now, Let's traduce the table index to CodObra in order to export the nears works of each work base on "codObra"

In [11]:
booksweight.head()


id        c1        c2        c3        c4        c5        c6  \
codobra                                                                   
110       0 -0.069944  0.261876  0.279082 -0.003079  0.204972 -0.209111   
140       1  0.927947  0.973363 -1.187703 -0.668665 -0.070719 -0.089884   
160       2  1.155321 -0.011052  0.533303  0.634104 -1.456100  0.430736   
190       3 -0.260877  0.295407  0.194097  0.061888  0.233164 -0.171829   
210       4  0.671067  0.826471  0.689987  0.456756  0.439277  0.358300   

               c7        c8        c9       c10  
codobra                                          
110      0.039038 -0.186838 -0.042609 -0.014002  
140     -0.468329  0.746488  0.077941  0.817792  
160      1.472087 -1.881912  0.803114  1.844294  
190     -0.026542 -0.209496  0.041619  0.115344  
210     -0.095728  0.094837 -0.810357 -0.325304

In [67]:
import numpy as np

size = indices.shape[0]
indices_obras = np.zeros([size,10])

indices_obras.shape



(133989, 10)

In [66]:
def getCodObras(rowindices):
    codobras = np.zeros(10)
    for i in range(10):
        codobrai =  getCodObra(rowindices[i])
        codobras[i] = codobrai
        
    return  codobras    
       
codobras = getCodObras(indices[200])
print(codobras)


[  5590. 219771.  64103. 179171. 140669. 165576. 374013. 293639. 284051.
 144384.]


In [ ]:
for i in range(size):
    indices_obras[i] =  getCodObras(indices[i])


In [72]:
print(indices_obras[345])

[  9650.  10877. 146482. 345849.  30703.  96422. 337819. 381355. 199063.
 283548.]


In [71]:

cab = 'codobra, codobra, codobra,codobra,codobra,codobra,codobra,codobra,codobra,codobra'
np.savetxt("recomendacoes.csv", indices_obras, delimiter=',', header=cab)

